#!/usr/bin/env bash
# balancer install
sudo apt-get -y update
sudo apt-get install -y haproxy
lb_config =\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s
frontend samson
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 460916-web-01 100.26.227.3:80 check
    server 460916-web-02 100.26.227.3:80  check
    "
echo "$lb_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

sudo service haproxy restart
