#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -lt 13 ]; do
      echo "Hour: $hour"
      i=1
      while [ $i -le 59 ]; do
      	  echo "$i"
	  i=$((i+1))
      done
      hour=$((hour+1))
done
